name: Compile LaTeX and Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: TusharPatil_resume.tex
          compiler: pdflatex

      - name: Upload to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: TusharPatil_resume.pdf
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}
